
services:
  jellylooter:
    build: .
    container_name: jellylooter
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config:/config
      - /shared/media:/storage  # Change this!
    environment:
      - TZ=America/Los_Angeles