x-netvisor-env: &netvisor-env
  NETVISOR_LOG_LEVEL: ${NETVISOR_LOG_LEVEL:-info}
  NETVISOR_SERVER_PORT: ${NETVISOR_SERVER_PORT:-60072}
  NETVISOR_DAEMON_PORT: ${NETVISOR_DAEMON_PORT:-60073}

services:

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: netvisor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - /mnt/tank/configs/netvisor/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - netvisor

  server:
    image: mayanayza/netvisor-server:latest
    ports:
      - "${NETVISOR_SERVER_PORT:-60072}:${NETVISOR_SERVER_PORT:-60072}"
    environment:
      <<: *netvisor-env
      NETVISOR_DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/netvisor
      NETVISOR_WEB_EXTERNAL_PATH: /app/static
      NETVISOR_PUBLIC_URL: ${NETVISOR_PUBLIC_URL:-http://localhost:${NETVISOR_SERVER_PORT:-60072}}
      # How server reaches integrated daemon
      # 172.17.0.1 is Docker's default bridge gateway. If your's is different, make sure to change it.
      NETVISOR_INTEGRATED_DAEMON_URL: http://172.17.0.1:${NETVISOR_DAEMON_PORT:-60073}
    volumes:
      - /mnt/tank/configs/netvisor/data:/data
    depends_on:
      postgres:
        condition: service_healthy
      daemon:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - netvisor

daemon:
  image: mayanayza/netvisor-daemon:latest
  container_name: netvisor-daemon
  network_mode: host
  privileged: true
  restart: unless-stopped
  environment:
    # Server connection
    - NETVISOR_SERVER_URL=http://localhost:60072
    # Daemon configuration
    - NETVISOR_DAEMON_API_KEY=06f61b145434496ba613b12d82d521f3
    - NETVISOR_PORT=60073
    - NETVISOR_MODE=Push
    - NETVISOR_BIND_ADDRESS=0.0.0.0
    - NETVISOR_NAME=netvisor-daemon
    - NETVISOR_LOG_LEVEL=info
    - NETVISOR_HEARTBEAT_INTERVAL=30
    - NETVISOR_NETWORK_ID=5e9f529b-8c1e-440d-85c7-2c086b68b01b
  volumes:
    - daemon-config:/root/.config/daemon
    # Comment out the line below to disable docker discovery
    - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  daemon-config:


networks:
  netvisor:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1